repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: .*\.graphql

  - repo: local
    hooks:
    - id: ruff-format
      name: ruff format
      description: "Run 'ruff format' for extremely fast Python formatting"
      entry: ruff format --force-exclude
      language: python
      types_or: [python, pyi, jupyter]
      args: [ --preview ]
    - id: ruff-check
      name: ruff check
      description: "Run 'ruff check' for extremely fast Python linting"
      entry: ruff check --force-exclude
      language: python
      types_or: [ python, pyi, jupyter ]
      args: [ --preview ]


  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
      - id: bandit
        args: [ -ll ]

#  - repo: https://github.com/pylint-dev/pylint
#    rev: 23.9.1
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [ python ]
#        args:
#          [
#            "-rn", # Only display messages
#            "-sn", # Don't display the score
#          ]
#        language_version: python3.12
